In [28]:
%pylab inline
import numpy as np
import pyreadline

Populating the interactive namespace from numpy and matplotlib


In [29]:
a = 1 # bind object to a name
print type(a) # names do not have type, objects do
del a # remove a from namespace
a = 1234234234234234234234234
print type(a)
a = [1, 2, 3]
b = a
del a
# int 32bit
# long arbitrary precision autopromotion to long

<type 'int'>
<type 'long'>


In [30]:
from math import factorial

In [31]:
factorial(100)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000L

In [32]:
dir(math) # list of exports

['__doc__',
 '__name__',
 '__package__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'hypot',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'modf',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'trunc']

In [33]:
dir(b)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [36]:
# pyxll python in excel

In [40]:
f = 1.4 + 2.3
type(f) #float is 64bit

float

In [41]:
from decimal import Decimal

In [42]:
Decimal(1.4)

Decimal('1.399999999999999911182158029987476766109466552734375')

In [43]:
Decimal(2.3)

Decimal('2.29999999999999982236431605997495353221893310546875')

In [44]:
c = 2+1.5j

In [47]:
c

(2+1.5j)

In [49]:
1+2-(3*4//6)**5+(7%5) # % remainder, // devision

-27

In [53]:
2/3 # integer devision (floor of result)

0

In [61]:
def my_av(nums):
    return sum(nums)//len(nums)

In [62]:
my_av([1,2,3,4])

2

In [65]:
from __future__ import division # python 3 divide, not recommended 
1/2

0.5

In [66]:
1//2 # integer division


0

In [71]:
print floor(2.9)
print round(2.9)

2.0
3.0


In [74]:
np.max([1,2,3])

3

In [75]:
max

<function max>

In [77]:
max = 3 #shadow the builtin max

In [79]:
int(2.7); float(2) # instantiation of the class int / float class

2.0

In [82]:
b = 2.5
b += 0.5 # for now b = b + 0.5, 

In [92]:
def fn1(a, b, c):
    a = float(a)
    b = float(b)
    c = float(c)
    print __name__
    return (-b + sqrt(b**2 - 4*a*c))/(2*a)

In [90]:
fn1(-2, 3, 5)

__main__


-1.0

In [93]:
fn2 = fn1
fn2.__name__

'fn1'

In [104]:
# <, >, <=, >=, ==, !=
# Boolean is integer
# True = 1
# False = 0
True + True

2

In [107]:
# python short circuit

In [109]:
# 'and', 'or', 'not' are operators

In [112]:
chance = 0.73
0.0 <= chance <=1.0 # works, change comparisons

True

In [113]:
s = 'I\'m a string'

In [114]:
s1 = '\\ d'

In [117]:
s1 # represenation of the string, valid python expression

'\\ d'

In [118]:
print s1

\ d


In [119]:
"helo " + 'world'

'helo world'

In [122]:
"hello "*3 # repeatition

'hello hello hello '

In [123]:
len("hello")

5

In [124]:
#split, join, trim
s = "hello world again"

In [125]:
s.split()

['hello', 'world', 'again']

In [127]:
s.join('abc')

'ahello world againbhello world againc'

In [130]:
s.split

<function split>

In [134]:
space = ' | '
words = s.split()
space.join(words)

'hello | world | again'

In [135]:
a = '''
slkdjfslkdfjs
df
sdf
sdf

'''

In [136]:
s.replace("world", 'mars')


'hello mars again'

In [137]:
s.upper()

'HELLO WORLD AGAIN'

In [138]:
s.lower()

'hello world again'

In [140]:
s.strip() # trim

'hello world again'

In [141]:
repr(1.1+2.2)

'3.3000000000000003'

In [143]:
str(1.1) # human readable

'1.1'

In [144]:
import datetime as dt
lunch_time = dt.datetime(2017, 3,13,12,30)

In [145]:
time_now = dt.datetime.now()

In [146]:
time_till_lunch = lunch_time- time_now

In [148]:
time_till_lunch

datetime.timedelta(0, 977, 698000)

In [149]:
str(time_till_lunch)

'0:16:17.698000'

In [150]:
repr(time_till_lunch) # python representation

'datetime.timedelta(0, 977, 698000)'

In [152]:
'{0} is greater than {1}'.format(100,50.23333333333333)

'100 is greater than 50.2333333333'

In [159]:
first = "igor"
last = 'kim'
'{first}, {last}'.format(first=first, last=last)

'igor, kim'

In [160]:
print('[{x:5.0f}] [{x:5.1f}] [{x:5.2f}]'.format(x=pi))

[    3] [  3.1] [ 3.14]


In [163]:
print('[{0:<10s}] [{0:>10s}] [{0:^10s}]'.format('Python'))

[Python    ] [    Python] [  Python  ]


In [166]:
print('[{0:*<10s}] [{0:*>10s}] [{0:*^10s}]'.format('Python'))

[Python****] [****Python] [**Python**]


In [170]:
a = [10,11,12,13,14]
print a

[10, 11, 12, 13, 14]


In [171]:
[10, 11] + [12, 13]

[10, 11, 12, 13]

In [172]:
[10, 11] * 3

[10, 11, 10, 11, 10, 11]

In [173]:
[1] * 3

[1, 1, 1]

In [174]:
range(5)

[0, 1, 2, 3, 4]

In [175]:
type(range(5))

list

In [176]:
range(2,7)

[2, 3, 4, 5, 6]

In [178]:
range(2, 7, 2)

[2, 4, 6]

In [180]:
np.array([1,2,3])*3

array([3, 6, 9])

In [183]:
#avoid use of range

In [184]:
# convention start inclusive, stop exclusive always...

In [185]:
a = [10, 11, 12, 13, 14]
a[-1]

14

In [195]:
a[-0],a[-1],a[-2],a[-3],a[-4],a[-5] # bad do not use a[-n]

(10, 14, 13, 12, 11, 10)

In [196]:
a=[10,'eleven',[12,13]]

In [197]:
a

[10, 'eleven', [12, 13]]

In [198]:
a[2]

[12, 13]

In [199]:
a[2][0]

12

In [200]:
del a[0]

In [201]:
a

['eleven', [12, 13]]

In [204]:
a.append(17)
a

['eleven', [12, 13], 17, 17]

In [206]:
# "in" or "not in"
17 in a

True

In [207]:
12.0 in a

False

In [208]:
# containment is by equality

In [217]:
f = 1.4
type(f)

float

In [220]:
a = range(10, 15); a

[10, 11, 12, 13, 14]

In [221]:
a[1:3] # 1 inclusive, 3 exclusive

[11, 12]

In [222]:
a[:3]

[10, 11, 12]

In [223]:
a[2:]

[12, 13, 14]

In [224]:
a[-2:]

[13, 14]

In [225]:
a[:]

[10, 11, 12, 13, 14]

In [226]:
a[::2] # start, stop, step; first two are out

[10, 12, 14]

In [229]:
b = a[::2]

In [230]:
a

[10, 11, 12, 13, 14]

In [231]:
b[0]=333

In [232]:
a

[10, 11, 12, 13, 14]

In [233]:
# array append, count, extend - by list, index - search for index of, insert, pop - by index
# remove - by value, sort - in place, sorted - new list


In [234]:
b = [9.5, 9.25, 9.75, 9.50]

In [235]:
b.append(9.00)

In [236]:
b

[9.5, 9.25, 9.75, 9.5, 9.0]

In [241]:
np.max(b)

9.75

In [242]:
b.index(np.max(b))

2

In [243]:
b.remove(np.max(b));b

[9.5, 9.25, 9.5, 9.0]

In [244]:
b.pop(0)

9.5

In [245]:
b

[9.25, 9.5, 9.0]

In [246]:
# del imperative statement, pop is function

In [247]:
# insert at the begining of the list use 'deque'
# insert at the middle in 'google it!'

In [248]:
# = eval right hand side, left x is a pointer


In [250]:
x = range(10)

In [251]:
y = x

In [256]:
y[0] = 333; y

[333, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [258]:
x = 999; y = x; x += 1; y

999

In [259]:
# integers, strings, tuples,  are immutable

In [261]:
x = [1,2,3]

In [262]:
y = x
x

[1, 2, 3]

In [263]:
x.append(4); x

[1, 2, 3, 4]

In [266]:
x += [4,5,6]; x # list of override extends to x.extend([4,5,6])

[1, 2, 3, 4, 4, 5, 6, 4, 5, 6, 4, 5, 6]

In [279]:
ttt = [['.']*3]*3 ; ttt

[['.', '.', '.'], ['.', '.', '.'], ['.', '.', '.']]

In [280]:
ttt[0][0] = 'X'; ttt

[['X', '.', '.'], ['X', '.', '.'], ['X', '.', '.']]

In [281]:
x = [1,2,3]
y = x
x is y

True

In [282]:
x = 'x'
y = x
x is y

True

In [283]:
x = 'x'
y = 'x'
x is y

True

In [284]:
# immutible strings and numbers

In [285]:
x = 1
y = 1
x is y

True

In [286]:
x = 1.0
y = 1.0
x is y

False

In [288]:
a = 10, 13, 14 # is a tuple
a = (10, 13, 14)

In [291]:
a = 10,
type(a)

tuple

In [295]:
a = [3, 4]
x = (1, 3, a)
x[-1].append(7); x

(1, 3, [3, 4, 7])

In [296]:
x = (1, 2, [3, 4, 7]) ; x

(1, 2, [3, 4, 7])

In [297]:
x[-1] += [8, 9, 10]

TypeError: 'tuple' object does not support item assignment

In [299]:
x

(1, 2, [3, 4, 7, 8, 9, 10])

In [302]:
def f(x):
    return 1, x, x**2

(a0, a1, a2) = f(3)

In [303]:
a0, a1, a2

(1, 3, 9)

In [304]:
a, b, c = [1, 2, 3]
print c, b, a

3 2 1


In [306]:
x = 99; y = 179
x, y = y, x
print x, y

179 99


In [312]:
record = {}

In [313]:
record['first'] = 'Jmes'
record['last'] = 'Maxwell'
record['born'] = 1831
print record

{'born': 1831, 'last': 'Maxwell', 'first': 'Jmes'}


In [315]:
new_record = {'first': 'James', 'middle': 'Clerk'}
record.update(new_record); record

{'born': 1831, 'first': 'James', 'last': 'Maxwell', 'middle': 'Clerk'}

In [316]:
# key must be hashable

In [317]:
hash('abc')

-1600925533

In [318]:
hash(23423423402934820394823049)

-794018082

In [319]:
hash((3,3,2,23,3))

-943677305

In [321]:
record['first1']

KeyError: 'first1'

In [327]:
record.get('first1', "TBD")

'TBD'

In [328]:
del record['middle']

In [331]:
record.pop('born', "NA")

'NA'

In [332]:
barn = {'cows': 1, 'dogs':5, 'cats':3}

In [333]:
'chikens' in barn

False

In [334]:
barn.keys()

['cows', 'cats', 'dogs']

In [335]:
barn.values()

[1, 3, 5]

In [336]:
# kyes and values are in the same order

In [337]:
barn.items()

[('cows', 1), ('cats', 3), ('dogs', 5)]

In [339]:
barn['rats'] = 100

In [340]:
barn.items()

[('cows', 1), ('cats', 3), ('rats', 100), ('dogs', 5)]

In [346]:
hash('cows')

-993054312

In [350]:
s = set() ; print s
t = set([1,2,3,1]) ; print t

set([])
set([1, 2, 3])


In [352]:
t.add(5) ; print t

set([1, 2, 3, 5])


In [353]:
a = {1, 2, 3, 4}
b = {3, 4, 5, 6}

In [356]:
a.union(b)
a | b # union operator

{1, 2, 3, 4, 5, 6}

In [357]:
# intersection, difference, symmetric_intersection

In [364]:
my_list = range(10**7)
%timeit 9632303 in my_list

10 loops, best of 3: 153 ms per loop


In [362]:
my_set = set(my_list)

In [365]:
%timeit 9632303 in my_set

The slowest run took 38.30 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 49.6 ns per loop


In [366]:
# falsy zero, None, "", [], empty set, and dict are falsy

In [368]:
tasks = ['A', 'B', 'C']
while tasks:
    curr = tasks.pop()
    print 'doing', curr

doing C
doing B
doing A


In [369]:
# while True: break

In [370]:
for i in range(5):
    print(i)

0
1
2
3
4


In [371]:
# iterable strings, tuples

In [ ]:
# np slices are references

In [387]:
a = np.arange(25).reshape(5,5)
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [384]:
print a[:,1::2], '\n'
print a[1::2, :4:2] , '\n'
print a[-1,:], '\n'

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]] 

[[ 5  7]
 [15 17]] 

[20 21 22 23 24] 



In [386]:
indices = [1, 2, -3]
y = a[indices]
y

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14]])

In [412]:
mask = np.array([[1, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 0, 0, 1]], dtype=bool)


In [413]:
a[mask].reshape(2,2)

array([[ 0, 12],
       [16, 24]])

In [397]:
print a[a > 11]

[12 13 14 15 16 17 18 19 20 21 22 23 24]


In [398]:
print a[a % 3 == 0]

[ 0  3  6  9 12 15 18 21 24]


In [415]:
# fancy indexing creates new array copies



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [417]:
mask = np.array([[0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1],
                 [0, 0, 0, 0, 0]], dtype=bool)
print a[mask]

[ 1  7 13 19]


In [424]:
select = [range(0,4), range(1,5)]
print a[select]

[ 1  7 13 19]


In [425]:
np.diag(a, k=1)

array([ 1,  7, 13, 19])