In [6]:
%pylab inline
import numpy as np
import scipy as sp

Populating the interactive namespace from numpy and matplotlib


In [12]:
# list comprehension
a = [10, 21, 23, 11, 24]
[val + 1 for val in a]
[val + 1 for val in a if val > 15] #with filtering

[22, 24, 25]

In [15]:
animals = ['dogs', 'cats', 'chickens']
for i, a in enumerate(animals,start=1):
    print('index: {i} {a}'.format(i=i, a=a))

index: 1 dogs
index: 2 cats
index: 3 chickens


In [16]:
for a, b in zip(range(10), range(5)):
    print a, b

0 0
1 1
2 2
3 3
4 4


In [19]:
for v in reversed(range(10)):
    print v

9
8
7
6
5
4
3
2
1
0


In [25]:
pos, neg = {}, {}
values = {"A": -4, "B": 10, "C": -5, "D": 3}

# dictionary comprehension
pos = {key:value for key, value in values.items() if value > 0} ; pos

{'B': 10, 'D': 3}

In [30]:
# python by assigment
def add_sheep(animals):
    animals.append("sheep")
    
add_sheep(animals)

In [31]:
animals

['dogs', 'cats', 'chickens', 'sheep', 'sheep']

In [32]:
def add(x, y):
    """Add values and returns it"""
    return x + y

In [33]:
add(23,33)

56

In [34]:
add(23.3, 423.0)

446.3

In [35]:
add("lkjsdf", "slkdjf")

'lkjsdfslkdjf'

In [38]:
animals.copy()

AttributeError: 'list' object has no attribute 'copy'

In [40]:
animals * 1 is animals #works do not use

False

In [41]:
animals[:] is animals # the right way

False

In [49]:
def count_letter(s, l):
    '''Counts number of letter l in string s'''
    return s.lower().count(l.lower())

count_letter('Php, Perl, or Python?', 'p')
    

4

In [54]:
count_letter(l='p', 'abc') # position arguments first

SyntaxError: non-keyword arg after keyword arg (<ipython-input-54-7f3f7fd3bcb8>, line 1)

In [61]:
int("10101", base=2)

21

In [62]:
# default optional arguments
def quad(x, a=1, b=1, c=0):
    return a*x**2 + b*x +c

In [65]:
print quad(3)
print quad(3, 2, 3)

12
27


In [68]:
np.sin(numpy.pi)

1.2246467991473532e-16

In [69]:
from numpy import sin, pi
sin(pi)

1.2246467991473532e-16

In [81]:
f = open("APLpy.ipynb", 'r')

In [85]:
f.readline()

'{\n'

In [86]:
lines = f.readlines()

In [87]:
len(lines)

75

In [91]:
f.close()
open?

In [93]:
from io import open
with open("APLpy.ipynb", encoding='ascii') as f:
    lines = f.readlines()

In [94]:
lines[0]

u'{\n'

In [101]:
s = u"the \N{MINUS SIGN} \u1F4A9"
print s

the − Ὂ9


In [104]:
%pwd

u'C:\\Apps\\0Projects\\xbiosckon\\python_training'

In [122]:
b = [9.5, 9.25, 9.75, 9.5]

fn = 'course_data.txt'
with open(fn,'w') as f:
    for n in b:
        f.write(u'{0}\n'.format(n))

c = []
with open(fn, 'r') as f:
    for l in f.readlines():
        c.append(float(l.strip()))
print c
        
with open(fn, 'a') as f:
    f.write(u'{0}\n'.format(9))
    
!type course_data.txt

[9.5, 9.25, 9.75, 9.5]
9.5
9.25
9.75
9.5
9


In [124]:
t = np.linspace(0, 2*np.pi, 50)
x = np.sin(t)
y = np.cos(t)

....

In [126]:
a = np.array([1,2,3,4])
type(a)

numpy.ndarray

In [127]:
print a.shape
print a.dtype

(4L,)
int32


In [130]:
print a.ndim
print a.itemsize

1
4


In [139]:
a = np.array([1,2,3,4.0])
b = np.array([2,3,4,5])
print a + b
print a * b
print a**b

[ 3.  5.  7.  9.]
[  2.   6.  12.  20.]
[  1.00000000e+00   8.00000000e+00   8.10000000e+01   1.02400000e+03]


In [141]:
a*=2.2
print a

[  4.4   8.8  13.2  17.6]


In [142]:
# array dtype does not change, it simply drops
print a.dtype

float64


In [143]:
a = np.array([[ 0,  1, 2,   3], 
              [10, 11, 12, 13]])

In [144]:
print a.shape
print a.size
print a.itemsize

(2L, 4L)
8
4


In [147]:
a[1,3]

13

In [148]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [151]:
a.base # if present shares if not owns data

In [152]:
a.nbytes

32

In [153]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [154]:
# load file np.loadtext()
# np.savetext()
# min, argmin, 
# max, argmax, 
# unravel_index(a.argmin(), a.shape)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [155]:
a = np.arange(-15, 15).reshape(5, 6) **2

In [156]:
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [158]:
np.max(a, axis=1)

array([225,  81,   9,  64, 196])

In [159]:
np.mean(a, axis=0)

array([ 81.,  76.,  73.,  72.,  73.,  76.])

In [160]:
np.min(a)

0

In [169]:
np.unravel_index(np.argmin(a), a.shape)

(2, 3)

In [170]:
np.where(a == a.min())

(array([2], dtype=int64), array([3], dtype=int64))

In [173]:
a[1,1]=0
np.where(a == a.min())

(array([1, 2], dtype=int64), array([1, 3], dtype=int64))